name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Verify Node.js and npm installation
        run: |
          node -v
          npm -v

      - name: List project directory
        run: ls -la

      - name: List node_modules directory
        run: ls -la node_modules

      - name: Check if features directory exists
        run: |
          if [ ! -d "features" ]; then
            echo "features directory does not exist"
            exit 1
          fi

      - name: Check if features/uploadFile.feature exists
        run: |
          if [ ! -f "features/uploadFile.feature" ]; then
            echo "features/uploadFile.feature does not exist"
            exit 1
          fi

      - name: Check if cucumber-js is installed
        run: |
          if [ ! -f "node_modules/.bin/cucumber-js" ]; then
            echo "cucumber-js does not exist in node_modules/.bin"
            exit 1
          fi

      - name: Grant execute permissions to cucumber-js
        run: chmod +x ./node_modules/.bin/cucumber-js

      - name: Install Chrome browser
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Install ChromeDriver
        run: |
          sudo apt-get install -yqq unzip
          CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -sS -o /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip"
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Ensure chromedriver is in the PATH
        run: |
          echo $PATH
          which chromedriver

      - name: Run tests
        run: ./node_modules/.bin/cucumber-js features/uploadFile.feature
