name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Grant execute permissions to cucumber-js
        run: chmod +x ./node_modules/.bin/cucumber-js

      - name: Run tests
        run: npx cucumber-js features/uploadFile.feature
